<?php
/**
 * File Description:
 * {{ModuleNamespace}}_{{ModuleName}}'s Index Controller
 *
 * File Name Restrictions:
 * This file MUST be named IndexController.phtml
 *
 * File Location:
 * app/code/local/$ModuleNamespace/$ModuleName/controllers/IndexController.phtml
 * ("local" can be either local or community")
 *
 * All comments can be safely deleted if desired!
 *---------------------------------------------------
 * Info from http://www.magentocommerce.com/knowledge-base/entry/magento-for-dev-part-3-magento-controller-dispatch
 *
 * How should Action Controllers be named?  Remember the <module> tag back
 * in config.xml?
 * 
 * <module>Magentotutorial_Helloworld</module> An Action Controller's name will
 *
 * Start with this string specified in config.xml (Magentotutorial_Helloworld) Be
 * followed by an underscore (Magentotutorial_Helloworld_) Which will be followed
 * by the Action Controller's name (Magentotutorial_Helloworld_Index) And finally,
 * the word "Controller" (Magentotutorial_Helloworld_IndexController) All Action
 * Controllers need Mage_Core_Controller_Front_Action as an ancestor.
 */

	/**
	 * Index Controller for {{ModuleNamespace}}_{{ModuleName}}
	 * Called when url is www.example.com/{{modulefrontname}}/index/*
	 * 
	 * In the example above, 'index' refers to "Index" in "_IndexController".
	 */
	class {{ModuleNamespace}}_{{ModuleName}}_IndexController extends Mage_Core_Controller_Front_Action {        

	/**
	 * Index Action for {{ModuleNamespace}}_{{ModuleName}}
	 * Called when url
	 * IS www.example.com/{{modulefronname}}/index/index/
	 * OR www.example.com/{{modulefronname}}/index/
	 * OR www.example.com/{{modulefronname}}/
	 */
    public function indexAction() {
		echo 'Index Action for {{ModuleNamespace}}_{{ModuleName}}!';
    }
}
